# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb1336a10a437f737b34b05d665cc0e91e0447a61872059806f873d82ab5a50deb2912fc9053f67ab3981980d26decae45e0b0618f9f1b16fc0bd3b86c8cbb87

test:
  secret_key_base: 3eca9dc8799dc1c502376bd0ba23ebaeeb18d806b3886f113845ca0ce7061e0447f42c5cfe75ac77e26452c7691502a3500c4fd1b333709e4e8ca0ab8d81b982

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
